# Generated by Django 3.2 on 2024-01-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Сатегории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Цена за товар')),
                ('image', models.ImageField(upload_to='menu/', verbose_name='Внешний вид товара')),
                ('type_of_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_menu', to='Client.chapter')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Готово/Не готово')),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество блюд')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбор для покупки')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Заказано/не заказано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Client.menu', verbose_name='Заказ')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_id', to='Client.order', verbose_name='Номер заказа')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
