# Generated by Django 3.2 on 2023-10-28 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type_of_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_menu', to='Client.chapter'),
        ),
        migrations.CreateModel(
            name='OrdersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество блюд')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Client.menu', verbose_name='Заказ')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
