# Generated by Django 3.2 on 2023-10-28 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0002_auto_20231028_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
