# Generated by Django 3.2 on 2024-01-05 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0002_auto_20240105_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordersitem',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='Client.order', verbose_name='Номер заказа'),
        ),
    ]
