# Generated by Django 3.2 on 2023-10-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_ordersitem_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Client.menu', verbose_name='Заказ'),
        ),
    ]
