# Generated by Django 3.2 on 2023-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_ordersitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Выбор для покупки'),
        ),
    ]
