# Generated by Django 3.2 on 2023-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_cook',
            field=models.BooleanField(default=False),
        ),
    ]
