# Generated by Django 3.2 on 2023-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_myuser_is_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_cook',
            field=models.BooleanField(default=False),
        ),
    ]
